// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbHt69YOzrZTOdx_FYRDgOeWt-FNgKD_k',
    appId: '1:389374610122:web:95e357a076faf51e394233',
    messagingSenderId: '389374610122',
    projectId: 'flutter-app-97525',
    authDomain: 'flutter-app-97525.firebaseapp.com',
    databaseURL: 'https://flutter-app-97525-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-97525.appspot.com',
    measurementId: 'G-EVKZ3KYBFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfLD7a1lLXM5P3om7_rIkjflGO8XEt9z0',
    appId: '1:389374610122:android:9b17b092cfddb913394233',
    messagingSenderId: '389374610122',
    projectId: 'flutter-app-97525',
    databaseURL: 'https://flutter-app-97525-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-97525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbgzmsCJpCbeIDjTvFlGao_pvMwT98x5M',
    appId: '1:389374610122:ios:b6905df37955312e394233',
    messagingSenderId: '389374610122',
    projectId: 'flutter-app-97525',
    databaseURL: 'https://flutter-app-97525-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-97525.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbgzmsCJpCbeIDjTvFlGao_pvMwT98x5M',
    appId: '1:389374610122:ios:b6905df37955312e394233',
    messagingSenderId: '389374610122',
    projectId: 'flutter-app-97525',
    databaseURL: 'https://flutter-app-97525-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-97525.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbHt69YOzrZTOdx_FYRDgOeWt-FNgKD_k',
    appId: '1:389374610122:web:ce96de3b9406cd4e394233',
    messagingSenderId: '389374610122',
    projectId: 'flutter-app-97525',
    authDomain: 'flutter-app-97525.firebaseapp.com',
    databaseURL: 'https://flutter-app-97525-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-97525.appspot.com',
    measurementId: 'G-NDQK3XH83V',
  );
}
